### PR TITLE
exposing SR tables through NodeManager

### PR DESCRIPTION
**Pull request by kkroo**
- Adding the ability to specify `match` field for filtering on `command: 'subscribers'`. This is needed for selecting individual subscribers
- Adding `fields` filtering for selection on reading from tables rather than returning the entire table row.

### CODE REVIEW

**Comment by shaddi** [comment]
What testing has this been through?

**Comment by kkroo** [comment]
Not as rigorous of testing as could be.. I essentially ran requests on the REPL with openbts-python to make sure the filtering worked appropriately. For the selection fields, I also tested using a bad key and got back the NodeManager equivalent of a query execution error.

I'll push some integration tests with openbts-python for these particular changes.

**Comment by kkroo** [comment]
I've added cases to openbts-python to test these changes:

In regards to [live integration tests](https://github.com/endaga/openbts-python/blob/3e2b8fa30429b002398a329fa9d9e8b9b70fa728/integration_test.py#L75) we have:
- Select all subscribers
- Selecting a subscriber based off of a filter
- Update a subscriber
- Update a non-existent subscriber
- Read all SR table entries with selection a particular column
- Read all columns of a SR table entry

For the [unit tests](https://github.com/endaga/openbts-python/blob/subscriber_registry_tables/openbts/tests/sipauthserve_component_tests.py):
- Requesting all subscribers
- Requesting a subscriber using a filter
- Requesting a nonexistent subscriber using a filter
- Updating a nonexistent subscriber
- Requesting an entry from a SR table
- Requesting a non-existent table entry from the SR
- Updating an entry in the SR
- Updating a non-existent entry in the SR

**Comment by shaddi** [comment]
lgtm

**Pull request merged**
